<?php
session_start();
if (!isset($_SESSION['username'])) {
    header("Location: register_login.php");
    exit();
}

?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap" />
    <link rel="stylesheet" href="admin.css" />
  </head>
  <body>
    <div class="main-container">
      <div class="flex-column-ef">
        <div class="page-links">
          <button class="friend"><span class="data-modify">資料<br />修改</span></button>
          <button class="setting-button"><span class="rank-list-span">排行榜</span></button>
          <!-- <button class="logout-button"><span class="logout-span">登出</span></button> -->
          <form action="logout.php" method="post">
            <button class="logout-button" type="submit"><span class="logout-span">登出</span></button>
          </form>
        </div>
        <span class="restaurant-edit-span">新增/修改餐廳</span>
        <div class="modify-form"></div>
        <button class="save-button"><span class="save-span">儲存</span></button>
      </div>
      <div class="flex-column-e">
        <span class="restaurant-collection-system">餐廳收藏系統(管理員)</span>
        <span class="restaurant-name">餐廳名字</span>
        <div class="restaurant-name-2"></div>
        <button class="frame"><span class="search">搜尋</span></button>
        <div class="restaurant-table"></div>
      </div>
      <div class="line"></div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
