<?php
session_start();
if (!isset($_SESSION['username'])) {
    header("Location: register_login.php");
    exit();
}
?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap" />
    <link rel="stylesheet" href="search.css" />
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC064S8Zgb8lJGUeGG2-tX6vN2VFBW5bbM&language=zh-TW"></script>
    <script>
      let map;
      let marker;
      let circle;
      function initMap() {

        var location = new google.maps.LatLng(25.0151, 121.5340);
        var mapProp= {
            center: location,
            zoom: 13,
        };

        // https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions
        map = new google.maps.Map(document.getElementById("google-map"), mapProp);

        placeMarker(location);

        google.maps.event.addListener(map, 'click', function(event) {
            const location = event.latLng;
            placeMarker(location);
            placeCircle(location);
            map.panTo(location);
        });
      }

      function placeMarker(location) {
          if (marker) {
              marker.setMap(null);
          }
          marker = new google.maps.Marker({
              position: location,
              map: map
          });
      }

      function placeCircle(location) {
          if (circle) {
              circle.setMap(null);
          }
          circle = new google.maps.Circle({
              center:location,
              radius:2000,
              strokeColor:"#FF0000",
              strokeOpacity:0.8,
              strokeWeight:2,
              fillColor:"#FF0000",
              fillOpacity:0.1,
              map
          });
      }
    </script>
  </head>
  <body onload="initMap()">
    <div class="main-container">
      <div class="flex-row-af">
        <span class="restaurant-system">餐廳收藏系統</span>
        <div class="page-links">
          <button class="search-button"><span class="search">搜尋<br />餐廳</span></button>
          <button class="hope-button"><span class="hope">心願<br />清單</span></button>
          <button class="love-button"><span class="love">我的<br />最愛</span></button>
          <button class="friend-button"><span class="friend">好友</span></button>
          <form action="logout.php" method="post">
            <button class="logout-button" type="submit"><span class="logout">登出</span></button>
          </form>
        </div>
      </div>
      <div class="flex-row-d">
        <div class="restaurant-table"></div>
        <div id="google-map"></div>
        <button class="button">
          <span class="start-search">開始搜尋</span></button
        ><span class="search-condition">搜尋條件</span>
        <div class="radius-input"></div>
        <span class="radius">半徑</span>
        <div class="search-condition-input"></div>
      </div>
      <div class="line"></div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
